"""Allow member_id, book_id on transactions to be NULL

Revision ID: 2c40ee86b96d
Revises: 52ddcf3f075c
Create Date: 2021-09-10 16:45:49.228028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c40ee86b96d'
down_revision = '52ddcf3f075c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
