"""Add unique=True on isbn and isbn13 fields

Revision ID: 3f8d54a758a2
Revises: 9e62b5321d79
Create Date: 2021-09-08 20:47:19.666078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f8d54a758a2"
down_revision = "9e62b5321d79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books", "isbn", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column(
        "books", "isbn13", existing_type=sa.VARCHAR(length=13), nullable=False
    )
    op.drop_index("ix_books_isbn", table_name="books")
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.drop_index("ix_books_isbn13", table_name="books")
    op.create_index(op.f("ix_books_isbn13"), "books", ["isbn13"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_isbn13"), table_name="books")
    op.create_index("ix_books_isbn13", "books", ["isbn13"], unique=False)
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.create_index("ix_books_isbn", "books", ["isbn"], unique=False)
    op.alter_column(
        "books", "isbn13", existing_type=sa.VARCHAR(length=13), nullable=True
    )
    op.alter_column("books", "isbn", existing_type=sa.VARCHAR(length=10), nullable=True)
    # ### end Alembic commands ###
