"""Add ondelete SET NULL to transactions foreign keys

Revision ID: 52ddcf3f075c
Revises: 1e03450b3a8a
Create Date: 2021-09-09 11:22:10.818724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ddcf3f075c'
down_revision = '1e03450b3a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_member_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_book_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'books', ['book_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'members', ['member_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_book_id_fkey', 'transactions', 'books', ['book_id'], ['id'])
    op.create_foreign_key('transactions_member_id_fkey', 'transactions', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###
