"""Remove book_id from books, add total_stock and rent_per_day

Revision ID: 6fb39a83faf1
Revises: c8d5cd3a7733
Create Date: 2021-09-07 11:31:19.107428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fb39a83faf1"
down_revision = "c8d5cd3a7733"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("total_stock", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("rent_per_day", sa.Integer(), nullable=True))
    op.drop_index("ix_books_book_id", table_name="books")
    op.drop_column("books", "book_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_books_book_id", "books", ["book_id"], unique=False)
    op.drop_column("books", "rent_per_day")
    op.drop_column("books", "total_stock")
    # ### end Alembic commands ###
