"""Add dues_paid to members table

Revision ID: 9e62b5321d79
Revises: e9d0a38b9f1f
Create Date: 2021-09-07 12:53:39.967678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e62b5321d79'
down_revision = 'e9d0a38b9f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('dues_paid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_members_dues_paid'), 'members', ['dues_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_dues_paid'), table_name='members')
    op.drop_column('members', 'dues_paid')
    # ### end Alembic commands ###
