"""Add book_id to books table

Revision ID: c8d5cd3a7733
Revises: 47917f7b80dd
Create Date: 2021-09-06 21:17:25.939460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d5cd3a7733'
down_revision = '47917f7b80dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_column('books', 'book_id')
    # ### end Alembic commands ###
